### ISSUE TITLE
print stylesheet

### ISSUE THREAD

**Issue by jampy** [greglobinski/gatsby-starter-personal-blog#18] opened 2018-04-11 17:07 UTC
The design is not printer-friendly as just a single page is printed (the mobile design is applied to the whole page).

I might try to create a appropriate print CSS and will create a PR, but it might take a couple of days...

**Comment by greglobinski** [comment] 2018-04-11 18:29
@jampy , you are right. the issue is still on the to-do, I almost forgot about it.
 Sure, your PR will be welcome, take your time.

**Comment by khairendra** [comment] 2018-05-11 03:10
Currently, I am able print correctly by adding [react-to-print](https://github.com/gregnb/react-to-print), it is quite easy.

But i think @greglobinski is working on it, i think i better wait for it at the moment.

**Comment by greglobinski** [comment] 2018-06-18 10:59
Print styleshets are fixed now for post screens in ver 1.1.1

**Closed by greglobinski** 2018-06-18 10:59 UTC
