### ISSUE TITLE
Fails out of the box

### ISSUE THREAD

**Issue by arlobelshee** [greglobinski/gatsby-starter-personal-blog#40] opened 2018-05-28 00:58 UTC
I'm on Windows, in case that matters.

After I create a new site (on any of head, v1.0.6, or v1.0.7) and then install sharp, gatsby develop crashes with compile errors. These differ slightly by version.

on 1.0.6:

```
 ERROR  Failed to compile with 2 errors                                                                         17:47:26

This dependency was not found:

* @material-ui/core/TextField in ./~/react-material-ui-form-validator/lib/SelectValidator.js, ./~/react-material-ui-form-validator/lib/TextValidator.js

To install it, you can run: npm install --save @material-ui/core/TextField
```

Except, of course, that that npm command fails as it can't find a package.json in the appropriate directory.

On HEAD or 1.0.7:

```
 error  in ./src/images/svg-icons/twitter.svg

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize ([site]\node_modules\prettier\index.js:7051:13)
    at formatWithCursor ([site]\node_modules\prettier\index.js:10370:12)
    at [site]\node_modules\prettier\index.js:31115:15
    at Object.format ([site]\node_modules\prettier\index.js:31134:12)
    at _default ([site]\node_modules\svgr\lib\plugins\prettier.js:10:50)
    at [site]\node_modules\svgr\lib\index.js:96:61
    at Generator.next (<anonymous>)
    at step ([site]\node_modules\svgr\lib\index.js:61:221)
    at _next ([site]\node_modules\svgr\lib\index.js:61:409)
    at tryCatch ([site]\node_modules\es6-promise\dist\es6-promise.js:416:12)
    at invokeCallback ([site]\node_modules\es6-promise\dist\es6-promise.js:431:13)
    at [site]\node_modules\es6-promise\dist\es6-promise.js:177:16
    at flush ([site]\node_modules\es6-promise\dist\es6-promise.js:126:5)
    at process._tickCallback (internal/process/next_tick.js:112:11)

 @ ./src/components/InfoBox/SocialIcons.js 26:15-60
```

(and a whole bunch of similar ones, for most of the other SVG files. Perhaps all? Don't know.)

I don't know how to recover from either of these errors, and I would really hope for the starter-created-site to work out of the box.

**Comment by greglobinski** [comment] 2018-05-28 07:54
@arlobelshee 

Sorry, I can't reproduce your problem. 

You should not 'then install sharp' after  `gatsby new [NEW_SITE_DIRECTORY_FOR_YOUR_BLOG] https://github.com/greglobinski/gatsby-starter-personal-blog.git`. You should have sharp already installed. If you have to, that means there is a problem with sharp installation, regrettably it happens on Windows. (I'm also on it).

Only I can suggest now is to remove your `node_packages` directory and do `yarn install` from scratch. If the sharp is already properly installed that could help.

**Comment by arlobelshee** [comment] 2018-05-28 15:53
Interestingly, I don't see yarn in the list of npm dependencies. I try to keep my machine with nothing installed globally (because every project needs different things and versions). So there is no yarn on my machine. Similarly, can't really install sharp first without it being global.

Is there a way to get your starter to work without global dependencies? What deps would you have to add to get that working?

**Comment by greglobinski** [comment] 2018-05-28 15:59
@arlobelshee 

[yarn[(https://yarnpkg.com/en/) is a package manager the same way as npm is. I just use it instead of npm, but you can use npm if you prefer. 
About sharp on Windows please read https://www.gatsbyjs.org/docs/gatsby-on-windows/

Good luck

**Comment by arlobelshee** [comment] 2018-05-28 16:28
Looks like the core problem is svgr failing for an unspecified reason, when it "can't infer a parser" for something. I know nothing about svgr. Any ideas what it is trying and failing to do?

**Comment by greglobinski** [comment] 2018-05-28 16:47
@arlobelshee 
Sorry, no idea, as I said, can't reproduce.
But just for clarification. You do `gatsby new [NEW_SITE_DIRECTORY_FOR_YOUR_BLOG] https://github.com/greglobinski/gatsby-starter-personal-blog.git` with no error and then with `gatsby develop` you get error about svg-icons? Am I right?

**Comment by arlobelshee** [comment] 2018-05-28 17:11
Correct.

**Comment by arlobelshee** [comment] 2018-05-28 18:19
PS [sites]> gatsby new arlobelshee.com https://github.com/greglobinski/gatsby-starter-personal-blog.git

info Creating new site from git: https://github.com/greglobinski/gatsby-starter-personal-blog.git
Cloning into 'arlobelshee.com'...
remote: Counting objects: 1913, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 1913 (delta 0), reused 8 (delta 0), pack-reused 1905
Receiving objects: 100% (1913/1913), 13.27 MiB | 8.01 MiB/s, done.
Resolving deltas: 100% (1117/1117), done.
success Created starter directory layout
info Installing packages...
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

> sharp@0.20.2 install [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-win32-x64.tar.gz
info sharp Creating [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release
info sharp Copying DLLs from [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\vendor\lib to [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=9.9.0 runtime=node arch=x64 platform=win32)

[sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
     Creating library [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\libvips-cpp.lib and object [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\libvips-cpp.exp
  Generating code
  All 1060 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  libvips-cpp.vcxproj -> [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\\libvips-cpp.dll
  libvips-cpp.vcxproj -> [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\libvips-cpp.pdb (Full PDB)
  common.cc
  metadata.cc
  stats.cc
  operations.cc
  pipeline.cc
  sharp.cc
  utilities.cc
  win_delay_load_hook.cc
     Creating library [sites]\arlobelshee.com\node_modules\
  gatsby-plugin-manifest\node_modules\sharp\build\Release\sharp.lib and object [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\sharp.exp
  Generating code
  All 1440 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  sharp.vcxproj -> [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\\sharp.node
  sharp.vcxproj -> [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release\sharp.pdb (Full PDB)
info sharp Creating [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release
info sharp Copying DLLs from [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\vendor\lib to [sites]\arlobelshee.com\node_modules\gatsby-plugin-manifest\node_modules\sharp\build\Release

> sharp@0.20.2 install [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-win32-x64.tar.gz
info sharp Creating [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release
info sharp Copying DLLs from [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\vendor\lib to [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=9.9.0 runtime=node arch=x64 platform=win32)

[sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
     Creating library [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\libvips-cpp.lib and object [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\libvips-cpp.exp
  Generating code
  All 1060 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  libvips-cpp.vcxproj -> [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\\libvips-cpp.dll
  libvips-cpp.vcxproj -> [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\libvips-cpp.pdb (Full PDB)
  common.cc
  metadata.cc
  stats.cc
  operations.cc
  pipeline.cc
  sharp.cc
  utilities.cc
  win_delay_load_hook.cc
     Creating library [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\sharp.lib and object [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release\sharp.exp
  Generating code
  All 1440 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  sharp.vcxproj -> [sites]\arlobelshee.com\node_modules\gat
  sby-plugin-sharp\node_modules\sharp\build\Release\\sharp.node
  sharp.vcxproj -> [sites]\arlobelshee.com\node_modules\gat
  sby-plugin-sharp\node_modules\sharp\build\Release\sharp.pdb (Full PDB)
info sharp Creating [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release
info sharp Copying DLLs from [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\vendor\lib to [sites]\arlobelshee.com\node_modules\gatsby-plugin-sharp\node_modules\sharp\build\Release

> sharp@0.20.0 install [sites]\arlobelshee.com\node_modules\sharp-cli\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-win32-x64.tar.gz
info sharp Creating [sites]\arlobelshee.com\node_modules\sharp-cli\node_modules\sharp\build\Release
info sharp Copying DLLs from [sites]\arlobelshee.com\node_modules\sharp-cli\node_modules\sharp\vendor\lib to [sites]\arlobelshee.com\node_modules\sharp-cli\node_modules\sharp\build\Release

> jss@9.8.1 postinstall [sites]\arlobelshee.com\node_modules\material-ui\node_modules\jss
> node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"

Love JSS? You can now support us on open collective:
 > https://opencollective.com/jss/donate

> cwebp-bin@4.0.0 postinstall [sites]\arlobelshee.com\node_modules\cwebp-bin
> node lib/install.js

  √ cwebp pre-build test passed successfully

> pngquant-bin@3.1.1 postinstall [sites]\arlobelshee.com\node_modules\pngquant-bin
> node lib/install.js

  √ pngquant pre-build test passed successfully
npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-material-ui-form-validator@2.0.0-beta.4 requires a peer of material-ui@next but none is installed. You must install peer dependencies yourself.
npm WARN redux-devtools-extension@2.13.2 requires a peer of redux@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN friendly-errors-webpack-plugin@1.7.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 2533 packages in 154.192s




PS [sites]> cd .\arlobelshee.com\

PS [sites]\arlobelshee.com> gatsby develop

success delete html and css files from previous builds — 0.006 s
success open and validate gatsby-config — 0.009 s
success copy gatsby files — 0.026 s
error UNHANDLED EXCEPTION


  Error: Cannot find module 'sharp'

  - v8-compile-cache.js:159 require
    [arlobelshee.com]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - extend-node-type.js:33 Object.<anonymous>
    [arlobelshee.com]/[gatsby-transformer-sharp]/extend-node-type.js:33:13

  - v8-compile-cache.js:178 Module._compile
    [arlobelshee.com]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - v8-compile-cache.js:159 require
    [arlobelshee.com]/[v8-compile-cache]/v8-compile-cache.js:159:20

  - gatsby-node.js:16 Object.<anonymous>
    [arlobelshee.com]/[gatsby-transformer-sharp]/gatsby-node.js:16:38

  - v8-compile-cache.js:178 Module._compile
    [arlobelshee.com]/[v8-compile-cache]/v8-compile-cache.js:178:30

  - module.js:11 require
    internal/module.js:11:18

  - api-runner-node.js:87 runAPI
    [arlobelshee.com]/[gatsby]/dist/utils/api-runner-node.js:87:20

  - api-runner-node.js:187
    [arlobelshee.com]/[gatsby]/dist/utils/api-runner-node.js:187:33


PS [sites]\arlobelshee.com> npm install --save-dev sharp

> sharp@0.20.2 install [sites]\arlobelshee.com\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-win32-x64.tar.gz
info sharp Creating [sites]\arlobelshee.com\node_modules\sharp\build\Release
info sharp Copying DLLs from [sites]\arlobelshee.com\node_modules\sharp\vendor\lib to [sites]\arlobelshee.com\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=9.9.0 runtime=node arch=x64 platform=win32)

[sites]\arlobelshee.com\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
     Creating library [sites]\arlobelshee.com\node_modules\sharp\build\Release\libvips-cpp.lib and object [sites]\arlobelshee.com\node_modules\sharp\build\Release\libvips-cpp.exp
  Generating code
  All 1060 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  libvips-cpp.vcxproj -> [sites]\arlobelshee.com\node_modules\sharp\build\Release\\libvips-cpp.dll
  libvips-cpp.vcxproj -> [sites]\arlobelshee.com\node_modules\sharp\build\Release\libvips-cpp.pdb (Full PDB)
  common.cc
  metadata.cc
  stats.cc
  operations.cc
  pipeline.cc
  sharp.cc
  utilities.cc
  win_delay_load_hook.cc
     Creating library [sites]\arlobelshee.com\node_modules\
  sharp\build\Release\sharp.lib and object [sites]\arlobelshee.com\node_modules\sharp\build\Release\sharp.exp
  Generating code
  All 1440 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  sharp.vcxproj -> [sites]\arlobelshee.com\node_modules\sharp\build\Release\\sharp.node
  sharp.vcxproj -> [sites]\arlobelshee.com\node_modules\sharp\build\Release\sharp.pdb (Full PDB)
info sharp Creating [sites]\arlobelshee.com\node_modules\sharp\build\Release
info sharp Copying DLLs from [sites]\arlobelshee.com\node_modules\sharp\vendor\lib to [sites]\arlobelshee.com\node_modules\sharp\build\Release
npm WARN eslint-plugin-graphql@2.1.1 requires a peer of graphql@^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN friendly-errors-webpack-plugin@1.7.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jss-template@1.0.1 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-material-ui-form-validator@2.0.0-beta.4 requires a peer of material-ui@next but none is installed. You must install peer dependencies yourself.
npm WARN redux-devtools-extension@2.13.2 requires a peer of redux@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ sharp@0.20.2
added 11 packages in 42.805s



PS [sites]\arlobelshee.com> gatsby develop

success delete html and css files from previous builds — 0.008 s
success open and validate gatsby-config — 0.010 s
success copy gatsby files — 0.025 s
success onPreBootstrap — 0.887 s
success source and transform nodes — 0.648 s
success building schema — 0.435 s
success createLayouts — 0.012 s
success createPages — 0.102 s
success createPagesStatefully — 0.033 s
success onPreExtractQueries — 0.004 s
success update schema — 0.118 s
success extract queries from components — 0.163 s
success run graphql queries — 2.770 s
success write out page data — 0.018 s
success write out redirect data — 0.006 s
Generating image thumbnails [==============================] 393/393 9.6 secs 100%

info bootstrap finished - 15.073 s

success onPostBootstrap — 0.001 s
 ERROR  Failed to compile with 14 errors                                                                        10:41:26

 error  in ./src/images/svg-icons/algolia-full.svg

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize ([sites]\arlobelshee.com\node_modules\prettier\index.js:7051:13)
    at formatWithCursor ([sites]\arlobelshee.com\node_modules\prettier\index.js:10370:12)
    at [sites]\arlobelshee.com\node_modules\prettier\index.js:31115:15
    at Object.format ([sites]\arlobelshee.com\node_modules\prettier\index.js:31134:12)
    at _default ([sites]\arlobelshee.com\node_modules\svgr\lib\plugins\prettier.js:10:50)
    at [sites]\arlobelshee.com\node_modules\svgr\lib\index.js:96:61
    at Generator.next (<anonymous>)
    at step ([sites]\arlobelshee.com\node_modules\svgr\lib\index.js:61:221)
    at _next ([sites]\arlobelshee.com\node_modules\svgr\lib\index.js:61:409)
    at tryCatch ([sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:416:12)
    at invokeCallback ([sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:431:13)
    at [sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:177:16
    at flush ([sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:126:5)
    at process._tickCallback (internal/process/next_tick.js:112:11)

 @ ./src/components/Page/PageHeader.js 18:19-69

 error  in ./src/images/svg-icons/github.svg

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize ([sites]\arlobelshee.com\node_modules\prettier\index.js:7051:13)
    at formatWithCursor ([sites]\arlobelshee.com\node_modules\prettier\index.js:10370:12)
    at [sites]\arlobelshee.com\node_modules\prettier\index.js:31115:15
    at Object.format ([sites]\arlobelshee.com\node_modules\prettier\index.js:31134:12)
    at _default ([sites]\arlobelshee.com\node_modules\svgr\lib\plugins\prettier.js:10:50)
    at [sites]\arlobelshee.com\node_modules\svgr\lib\index.js:96:61
    at Generator.next (<anonymous>)
    at step ([sites]\arlobelshee.com\node_modules\svgr\lib\index.js:61:221)
    at _next ([sites]\arlobelshee.com\node_modules\svgr\lib\index.js:61:409)
    at tryCatch ([sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:416:12)
    at invokeCallback ([sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:431:13)
    at [sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:177:16
    at flush ([sites]\arlobelshee.com\node_modules\es6-promise\dist\es6-promise.js:126:5)
    at process._tickCallback (internal/process/next_tick.js:112:11)

 @ ./src/components/InfoBox/SocialIcons.js 22:14-58

 error  in ./src/images/svg-icons/facebook.svg

<snip - same stack>

 @ ./src/components/InfoBox/SocialIcons.js 24:16-62

 error  in ./src/images/svg-icons/twitter.svg

<snip - same stack>

 @ ./src/components/InfoBox/SocialIcons.js 26:15-60

 error  in ./src/images/svg-icons/graphql.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 22:15-60

 error  in ./src/images/svg-icons/algolia.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 18:15-60

 error  in ./src/images/svg-icons/react.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 20:14-57

 error  in ./src/images/svg-icons/jss.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 24:11-52

 error  in ./src/images/svg-icons/material-ui.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 26:18-67

 error  in ./src/images/svg-icons/redux.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 28:13-56

 error  in ./src/images/svg-icons/gatsby.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 30:14-58

 error  in ./src/images/svg-icons/webpack.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 32:15-60

 error  in ./src/images/svg-icons/babel.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 34:13-56

 error  in ./src/images/svg-icons/netlify.svg

<snip - same stack>

 @ ./src/components/InfoBox/StackIcons.js 36:15-60

PS [sites]\arlobelshee.com>

**Comment by arlobelshee** [comment] 2018-05-28 18:41
Sure enough: it works fine when when I comment out the importing for the SVGs from SocialIcons.js, StackIcons.js, and PageHeader.js. So it is definitely the icons.

While you try to fix for your starter, I'll just use some different way to show SVG icons.

**Comment by greglobinski** [comment] 2018-05-28 22:44
@arlobelshee 
no questions, your problem is sharp installation. I suggest reading the GatsbyJS docs again
https://www.gatsbyjs.org/docs/gatsby-on-windows/

**Comment by arlobelshee** [comment] 2018-05-28 23:00
I don't buy that. The exception traces are from prettier, run by svgr, run when importing the svgs. How is sharp involved in that? Perttier should just be tidying up the whitespace for the output, right?

And when sharp wasn't installed, gatsby crashed saying sharp was missing. I fixed that easily. And *then* I got to the svg import bug.

**Comment by greglobinski** [comment] 2018-05-29 05:05
@arlobelshee 

"I fixed that easily". That's the clue. You think you did, but you did not.
You have the  rights to do not "buy" it. 

But I'm closing the thread as a not related to the starter's code.
Thanks.

**Closed by greglobinski** 2018-05-29 05:05 UTC
